apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.secret.name}}
  labels:
    app:  {{ .Values.labels.app }}
type:  {{.Values.secret.type}}
data:
  DB_USER: {{.Values.secret.data.dbUser}}
  DB_PASS: {{.Values.secret.data.dbPass}}
  MYSQL_ROOT_PASSWORD: {{.Values.secret.data.dbRootPass}}