apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{.Values.nameSpace.name}}
spec:
  selector:
    app: {{ .Values.labels.app }}
  type: {{ .Values.service.type }}
  ports:
  - protocol: {{ .Values.service.protocol }}
    port: {{ .Values.port.http }}
    targetPort: {{ .Values.port.http }}